export const getSummonerSpellName = (id) => {
  const spellMap = {
    1: "Boost",
    3: "Exhaust",
    4: "Flash",
    6: "Haste",
    7: "Heal",
    11: "Smite",
    12: "Teleport",
    13: "Mana",
    14: "Dot",
    21: "Barrier",
    32: "Snowball",
    2201: "CherryHold",
    2202: "CherryFlash"
  };
  return spellMap[id] || "Unknown Spell";
};

export const getQueueDescription = (queueId) => {
  const queueMap = {
    400: "Normal Draft",
    420: "Ranked Solo",
    430: "Normal Blind",
    440: "Ranked Flex",
    450: "ARAM",
    700: "Clash",
    900: "URF",
    1400: "Ultimate Spellbook",
    1700: "Arena"
  };
  return queueMap[queueId] || "Unknown Queue Type";
};

export const getRuneImage = (runeId) => {
  const runeMap = {
    8000: "7201_Precision.png",
    8100: "7200_Domination.png",
    8200: "7202_Sorcery.png",
    8300: "7203_Whimsy.png",
    8400: "7204_Resolve.png",

    8005: "Precision/PressTheAttack/PressTheAttack.png",
    8008: "Precision/LethalTempo/LethalTempoTemp.png",
    8021: "Precision/FleetFootwork/FleetFootwork.png",
    8010: "Precision/Conqueror/Conqueror.png",

    8112: "Domination/Electrocute/Electrocute.png",
    8128: "Domination/DarkHarvest/DarkHarvest.png",
    9923: "Domination/HailOfBlades/HailOfBlades.png",

    8214: "Sorcery/SummonAery/SummonAery.png",
    8229: "Sorcery/ArcaneComet/ArcaneComet.png",
    8230: "Sorcery/PhaseRush/PhaseRush.png",

    8351: "Inspiration/GlacialAugment/GlacialAugment.png",
    8360: "Inspiration/UnsealedSpellbook/UnsealedSpellbook.png",
    8369: "Inspiration/FirstStrike/FirstStrike.png",

    8437: "Resolve/GraspOfTheUndying/GraspOfTheUndying.png",
    8439: "Resolve/VeteranAftershock/VeteranAftershock.png",
    8465: "Resolve/Guardian/Guardian.png",
  };

  const baseURL = "https://ddragon.leagueoflegends.com/cdn/img/perk-images/Styles/";
  return runeId && runeMap[runeId] ? `${baseURL}${runeMap[runeId]}` : "Unknown Rune";
};

export const formatGameTime = (seconds) => {
  if (!seconds) return "00:00";
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  return `${minutes}:${remainingSeconds < 10 ? '0' : ''}${remainingSeconds}`;
};

export const getChampionData = (championId) => {
  const championMap = {
    266: { key: "Aatrox", name: "Aatrox" },
    103: { key: "Ahri", name: "Ahri" },
    84: { key: "Akali", name: "Akali" },
    166: { key: "Akshan", name: "Akshan" },
    12: { key: "Alistar", name: "Alistar" },
    799: { key: "Ambessa", name: "Ambessa" },
    32: { key: "Amumu", name: "Amumu" },
    34: { key: "Anivia", name: "Anivia" },
    1: { key: "Annie", name: "Annie" },
    523: { key: "Aphelios", name: "Aphelios" },
    22: { key: "Ashe", name: "Ashe" },
    136: { key: "AurelionSol", name: "Aurelion Sol" },
    893: { key: "Aurora", name: "Aurora" },
    268: { key: "Azir", name: "Azir" },
    432: { key: "Bard", name: "Bard" },
    200: { key: "Belveth", name: "Bel'Veth" },
    53: { key: "Blitzcrank", name: "Blitzcrank" },
    63: { key: "Brand", name: "Brand" },
    201: { key: "Braum", name: "Braum" },
    233: { key: "Briar", name: "Briar" },
    51: { key: "Caitlyn", name: "Caitlyn" },
    164: { key: "Camille", name: "Camille" },
    69: { key: "Cassiopeia", name: "Cassiopeia" },
    31: { key: "Chogath", name: "Cho'Gath" },
    42: { key: "Corki", name: "Corki" },
    122: { key: "Darius", name: "Darius" },
    131: { key: "Diana", name: "Diana" },
    119: { key: "Draven", name: "Draven" },
    36: { key: "DrMundo", name: "Dr. Mundo" },
    245: { key: "Ekko", name: "Ekko" },
    60: { key: "Elise", name: "Elise" },
    28: { key: "Evelynn", name: "Evelynn" },
    81: { key: "Ezreal", name: "Ezreal" },
    9: { key: "Fiddlesticks", name: "Fiddlesticks" },
    114: { key: "Fiora", name: "Fiora" },
    105: { key: "Fizz", name: "Fizz" },
    3: { key: "Galio", name: "Galio" },
    41: { key: "Gangplank", name: "Gangplank" },
    86: { key: "Garen", name: "Garen" },
    150: { key: "Gnar", name: "Gnar" },
    79: { key: "Gragas", name: "Gragas" },
    104: { key: "Graves", name: "Graves" },
    887: { key: "Gwen", name: "Gwen" },
    120: { key: "Hecarim", name: "Hecarim" },
    74: { key: "Heimerdinger", name: "Heimerdinger" },
    910: { key: "Hwei", name: "Hwei" },
    420: { key: "Illaoi", name: "Illaoi" },
    39: { key: "Irelia", name: "Irelia" },
    427: { key: "Ivern", name: "Ivern" },
    40: { key: "Janna", name: "Janna" },
    59: { key: "JarvanIV", name: "Jarvan IV" },
    24: { key: "Jax", name: "Jax" },
    126: { key: "Jayce", name: "Jayce" },
    202: { key: "Jhin", name: "Jhin" },
    222: { key: "Jinx", name: "Jinx" },
    145: { key: "Kaisa", name: "Kai'Sa" },
    429: { key: "Kalista", name: "Kalista" },
    43: { key: "Karma", name: "Karma" },
    30: { key: "Karthus", name: "Karthus" },
    38: { key: "Kassadin", name: "Kassadin" },
    55: { key: "Katarina", name: "Katarina" },
    10: { key: "Kayle", name: "Kayle" },
    141: { key: "Kayn", name: "Kayn" },
    85: { key: "Kennen", name: "Kennen" },
    121: { key: "Khazix", name: "Kha'Zix" },
    203: { key: "Kindred", name: "Kindred" },
    240: { key: "Kled", name: "Kled" },
    96: { key: "KogMaw", name: "Kog'Maw" },
    897: { key: "KSante", name: "K'Sante" },
    7: { key: "Leblanc", name: "LeBlanc" },
    64: { key: "LeeSin", name: "Lee Sin" },
    89: { key: "Leona", name: "Leona" },
    876: { key: "Lillia", name: "Lillia" },
    127: { key: "Lissandra", name: "Lissandra" },
    236: { key: "Lucian", name: "Lucian" },
    117: { key: "Lulu", name: "Lulu" },
    99: { key: "Lux", name: "Lux" },
    54: { key: "Malphite", name: "Malphite" },
    90: { key: "Malzahar", name: "Malzahar" },
    57: { key: "Maokai", name: "Maokai" },
    11: { key: "MasterYi", name: "Master Yi" },
    800: { key: "Mel", name: "Mel" },
    902: { key: "Milio", name: "Milio" },
    21: { key: "MissFortune", name: "Miss Fortune" },
    62: { key: "MonkeyKing", name: "Wukong" },
    82: { key: "Mordekaiser", name: "Mordekaiser" },
    25: { key: "Morgana", name: "Morgana" },
    950: { key: "Naafiri", name: "Naafiri" },
    267: { key: "Nami", name: "Nami" },
    75: { key: "Nasus", name: "Nasus" },
    111: { key: "Nautilus", name: "Nautilus" },
    518: { key: "Neeko", name: "Neeko" },
    76: { key: "Nidalee", name: "Nidalee" },
    895: { key: "Nilah", name: "Nilah" },
    56: { key: "Nocturne", name: "Nocturne" },
    20: { key: "Nunu", name: "Nunu & Willump" },
    2: { key: "Olaf", name: "Olaf" },
    61: { key: "Orianna", name: "Orianna" },
    516: { key: "Ornn", name: "Ornn" },
    80: { key: "Pantheon", name: "Pantheon" },
    78: { key: "Poppy", name: "Poppy" },
    555: { key: "Pyke", name: "Pyke" },
    246: { key: "Qiyana", name: "Qiyana" },
    133: { key: "Quinn", name: "Quinn" },
    497: { key: "Rakan", name: "Rakan" },
    33: { key: "Rammus", name: "Rammus" },
    421: { key: "RekSai", name: "Rek'Sai" },
    526: { key: "Rell", name: "Rell" },
    888: { key: "Renata", name: "Renata Glasc" },
    58: { key: "Renekton", name: "Renekton" },
    107: { key: "Rengar", name: "Rengar" },
    92: { key: "Riven", name: "Riven" },
    68: { key: "Rumble", name: "Rumble" },
    13: { key: "Ryze", name: "Ryze" },
    360: { key: "Samira", name: "Samira" },
    113: { key: "Sejuani", name: "Sejuani" },
    235: { key: "Senna", name: "Senna" },
    147: { key: "Seraphine", name: "Seraphine" },
    875: { key: "Sett", name: "Sett" },
    35: { key: "Shaco", name: "Shaco" },
    98: { key: "Shen", name: "Shen" },
    102: { key: "Shyvana", name: "Shyvana" },
    27: { key: "Singed", name: "Singed" },
    14: { key: "Sion", name: "Sion" },
    15: { key: "Sivir", name: "Sivir" },
    72: { key: "Skarner", name: "Skarner" },
    901: { key: "Smolder", name: "Smolder" },
    37: { key: "Sona", name: "Sona" },
    16: { key: "Soraka", name: "Soraka" },
    50: { key: "Swain", name: "Swain" },
    517: { key: "Sylas", name: "Sylas" },
    134: { key: "Syndra", name: "Syndra" },
    223: { key: "TahmKench", name: "Tahm Kench" },
    163: { key: "Taliyah", name: "Taliyah" },
    91: { key: "Talon", name: "Talon" },
    44: { key: "Taric", name: "Taric" },
    17: { key: "Teemo", name: "Teemo" },
    412: { key: "Thresh", name: "Thresh" },
    18: { key: "Tristana", name: "Tristana" },
    48: { key: "Trundle", name: "Trundle" },
    23: { key: "Tryndamere", name: "Tryndamere" },
    4: { key: "TwistedFate", name: "Twisted Fate" },
    29: { key: "Twitch", name: "Twitch" },
    77: { key: "Udyr", name: "Udyr" },
    6: { key: "Urgot", name: "Urgot" },
    110: { key: "Varus", name: "Varus" },
    67: { key: "Vayne", name: "Vayne" },
    45: { key: "Veigar", name: "Veigar" },
    161: { key: "Velkoz", name: "Vel'Koz" },
    711: { key: "Vex", name: "Vex" },
    254: { key: "Vi", name: "Vi" },
    234: { key: "Viego", name: "Viego" },
    112: { key: "Viktor", name: "Viktor" },
    8: { key: "Vladimir", name: "Vladimir" },
    106: { key: "Volibear", name: "Volibear" },
    19: { key: "Warwick", name: "Warwick" },
    498: { key: "Xayah", name: "Xayah" },
    101: { key: "Xerath", name: "Xerath" },
    5: { key: "XinZhao", name: "Xin Zhao" },
    157: { key: "Yasuo", name: "Yasuo" },
    777: { key: "Yone", name: "Yone" },
    83: { key: "Yorick", name: "Yorick" },
    350: { key: "Yuumi", name: "Yuumi" },
    154: { key: "Zac", name: "Zac" },
    238: { key: "Zed", name: "Zed" },
    221: { key: "Zeri", name: "Zeri" },
    115: { key: "Ziggs", name: "Ziggs" },
    26: { key: "Zilean", name: "Zilean" },
    142: { key: "Zoe", name: "Zoe" },
    143: { key: "Zyra", name: "Zyra" }
  };
  return championMap[championId] || { key: "Unknown", name: "Unknown Champion" };
};
